name: "app-b"
service:
  type: ClusterIP
  http:
    name: http
    protocol: TCP
    externalPort: 8081
    internalPort: 8081
server:
  http:
    name: http
    protocol: TCP
    port: 8081
  image:
    repository: "this-is-a-placeholder-should-be-docker-repo-url"
    pullPolicy: IfNotPresent
config:
  logs:
    level: debug
  database:
    db_driver: postgres
    host: skaffold-workspace-postgres.skaffold-workspace
    port: 5432
    sslmode: enable
    db_name: workspacedb
    username: workspaceuser
    password: ayjXWHStdFOEROk4EQclrfwR3Lm4isHE9Hrh3rt
