apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: skaffold-workspace
build:
  local:
    concurrency: 1
    push: false
    useBuildkit: true
  artifacts:
    - image: shadysmaoui/app-a
      context: apps/app-a
      docker:
        dockerfile: Dockerfile
    - image: shadysmaoui/app-b
      context: apps/app-b
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: skaffold-workspace-app-a
        chartPath: apps/app-a/helm/
        skipBuildDependencies: true
        namespace: skaffold-workspace
        createNamespace: true
        upgradeOnChange: true
        setValues:
          image:
            repository: shadysmaoui/app-a

      - name: skaffold-workspace-app-b
        chartPath: apps/app-b/helm/
        skipBuildDependencies: true
        namespace: skaffold-workspace
        createNamespace: true
        upgradeOnChange: true
        setValues:
          server:
            image:
              repository: shadysmaoui/app-b

      - name: skaffold-workspace-postgres
        chartPath: infra/postgres/helm/
        setValues:
          postgresql:
            fullnameOverride: skaffold-workspace-postgres
            enabled: true
            auth:
              username: postgres
              password: postgres
              database: app_b_db
            primary:
              persistence:
                size: 100Mi

      - name: skaffold-workspace-minio
        chartPath: infra/minio/helm/
        setValues:
          minio:
            fullnameOverride: skaffold-workspace-minio
            enabled: true
            accessKey: admin
            secretKey: MinIoSecret
            service:
              type: NodePort
            replicas: 1
            persistence:
              size: 1Gi
            resources:
              requests:
                memory: 100Mi
            defaultBucket:
              enabled: true
              name: skaffold-workspace
    hooks:
      before:
        - host:
            command: ["sh", "-c", "kubectl create namespace skaffold-workspace --dry-run=client -o yaml | kubectl apply -f -"]
portForward:
  - resourceType: service
    namespace: "skaffold-workspace"
    resourceName: "app-a"
    port: 8080
    localPort: 8080
  - resourceType: service
    namespace: "skaffold-workspace"
    resourceName: "app-b"
    port: 8081
    localPort: 8081
  - resourceType: Service
    namespace: "skaffold-workspace"
    resourceName: "skaffold-workspace-minio"
    port: 9000
    localPort: 9000

