apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      imagePullSecrets:
        - name: registry-creds
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.server.image.repository }}
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.server.http.port }}
              protocol: {{ .Values.server.http.protocol }}
              name: {{ .Values.server.http.name }}
          env:
            - name: HTTP_SERVER_PORT
              value: {{ .Values.server.http.port | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.config.logs.level}}
            - name: DB_DRIVER
              value: {{ .Values.config.database.db_driver }}
            - name: DB_HOST
              value: {{ .Values.config.database.host }}
            - name: DB_PORT
              value: {{ .Values.config.database.port | quote}}
            - name: DB_SSLMODE
              value: {{ .Values.config.database.sslmode }}
            - name: DB_NAME
              value: {{ .Values.config.database.db_name | quote}}
            - name: DB_USERNAME
              value: {{ .Values.config.database.username }}
            - name: DB_PASSWORD
              value: {{ .Values.config.database.password }}
